### ISSUE TITLE
Procedure to make `CompositeFuture` accept promises?

### ISSUE THREAD

**Issue by theArnavPatil** [abhayc-glitch/sanguine#11]
I did that but now i get a `CompositeFuture` issue. It requires Futures as an argument. Is there a method or a procedure to return a promise that succeeds when all the promises are succeeded and failed when at least one of the promises is failed?

![Screen Shot 2021-09-04 at 3 24 21 PM](https://user-images.githubusercontent.com/78511893/132109356-1b87bca1-d688-4bc2-87ef-49dba51dae76.png)
_Originally posted by @abhayc-glitch in https://github.com/abhayc-glitch/sanguine/issues/10#issuecomment-913048336_

**Comment by Lee-Gen** [comment]
Hi I'm Lee
I'm new to open source contributions
But I'm really looking to forward to begin with it
If you could help me with what has to be done I could begin with this project

**Comment by abhayc-glitch** [comment]
Hey @Lee-Gen ,
Basically this is a AI Diary app and i'm in the Process of creating the backend right now. Im vertx with java as my backend framework and react for frontend. Im working deploying verticles right now and the things i have got through are: Creating Persistence and a Persistence test case as well as a register user test case. I have also added a HTTP verticle with base routers and API routers and a register user routing context. I hope to add MongoDB client so i get started on JWT and User Registration. Soon i will also add models for my app and define each aspect of it. 
Thank you for taking interest in this Project!

**Comment by theArnavPatil** [comment]
I feel like since your already checking fro errors in the `deployVerticle` promise already, there's no point in doing so again. In the future we can just add some test cases to replicate `CompositeFuture`'s behavior. Change your code to the following:
```
package com.server.backend;


import io.vertx.core.AbstractVerticle;
import io.vertx.core.Promise;

public class MainVerticle extends AbstractVerticle {
  @Override
  public void start(Promise<Void> startPromise) {
      deployVerticle(HttpVerticle.class.getName());
      deployVerticle(PersistenceVerticle.class.getName());
      // Dont need an onComplete because we already do that in the deployverticle?
  }

  Promise<Void> deployVerticle (String verticleName){
    Promise<Void> retVal = Promise.promise();
    vertx.deployVerticle(verticleName, event -> {
      if (event.succeeded()) {
        retVal.complete();
      }else{
        retVal.fail(event.cause());
      }
    });
    return retVal;
  }
}


```

**Comment by abhayc-glitch** [comment]
Thanks!

**Comment by abhayc-glitch** [comment]
Yes but the point of the `CompositeFuture` is to have an overall checker to see if all verticles have succeeded and then only run the application. If not then fail. So my question is how would I do that as a deployment checker. Should i manually create a method to do that?

**Comment by theArnavPatil** [comment]
I mean I guess for now we can continue with just the regular deployVerticle. Later once we get into unit testing then we can create a method for deploying succeeded verticles if they have varying test cases.
